baseURL: "https://amshrbo.github.io/"
languageCode: en-us
title: amshrbo Blog
theme: "PaperMod"

menu:
  main:
    - identifier: about_me
      name: About Me
      url: /about_me/
      weight: 10
    - identifier: archives
      name: archives
      url: /archives/
      weight: 20
    - identifier: categories
      name: categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: tags
      url: /tags/
      weight: 40
 

params:
  env: production
  homeInfoParams:
        Title: Welcome to my _space_   
        Content: 
                Hello there this is Ahmed Mohamed a passioniate ___machine learning engineer___ with a _Bachelor’s degree in Computer Science_ 
                Please visit my about page for more information about my experience.        
                In this blog I tackle diffrent topics in computer science.              

                
                
                `My Mission:` is to produce high quality content, So be assured that every article you will 
                find here will gonna add some value for _you or for me._
 
  
  socialIcons: 
    - name: linkedin
      url: "https://linkedin.com/in/amshrbo"
    - name: twitter
      url: "https://twitter.com/amshrbo"
    - name: github
      url: "https://github.com/amshrbo"



  ShowShareButtons: true
  ShowReadingTime: true
  author: "Ahmed Mohamed"
  
